spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: https://www.baidu.com/
          predicates:
            - Path=/red/{segment},/blue/{segment}
server:
  port: 8080
