spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8850/{segment}
        #  uri: http://ityouknow.com
        #  uri: https://example.org
          predicates:
            - Path=/test/{segment}
server:
  port: 8849
